//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "test.h"
#include <drogon/utils/OStringStream.h>
#include <drogon/utils/Utilities.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string test::genText(const DrTemplateData& test_view_data)
{
	drogon::OStringStream test_tmp_stream;
	std::string layoutName{""};
	test_tmp_stream << "<!DOCTYPE html>\n";
	test_tmp_stream << "<html lang=\"en\">\n";
    auto para=test_view_data.get<std::unordered_map<std::string,std::string,utils::internal::SafeStringHash>>("parameters");
	test_tmp_stream << "<head>\n";
	test_tmp_stream << "    <meta charset=\"UTF-8\">\n";
	test_tmp_stream << "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
	test_tmp_stream << "    <title>";
{
    auto & val=test_view_data["title"];
    if(val.type()==typeid(const char *)){
        test_tmp_stream<<*(std::any_cast<const char *>(&val));
    }else if(val.type()==typeid(std::string)||val.type()==typeid(const std::string)){
        test_tmp_stream<<*(std::any_cast<const std::string>(&val));
    }
}
	test_tmp_stream << "</title>\n";
	test_tmp_stream << "</head>\n";
	test_tmp_stream << "<body>\n";
	test_tmp_stream << "    parameter1 = ";
{
    auto & val=test_view_data["p1"];
    if(val.type()==typeid(const char *)){
        test_tmp_stream<<*(std::any_cast<const char *>(&val));
    }else if(val.type()==typeid(std::string)||val.type()==typeid(const std::string)){
        test_tmp_stream<<*(std::any_cast<const std::string>(&val));
    }
}
	test_tmp_stream << " <br>\n";
	test_tmp_stream << "    parameter2 = ";
{
    auto & val=test_view_data["p2"];
    if(val.type()==typeid(const char *)){
        test_tmp_stream<<*(std::any_cast<const char *>(&val));
    }else if(val.type()==typeid(std::string)||val.type()==typeid(const std::string)){
        test_tmp_stream<<*(std::any_cast<const std::string>(&val));
    }
}
	test_tmp_stream << " <br>\n";
	test_tmp_stream << "</body>\n";
	test_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(test_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = test_view_data;
auto str = std::move(test_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
